//ARRAYS
//76) Create a program that automatically fills a numeric vector with 7 numbers randomly
// generated by the computer and then displays the generated values on the screen.

package Java.Algorithms;

import java.util.Arrays;
import java.util.Random;

public class JavaAlgorithms076 {

    public static void main(String[] args) {

        int [] myArray = new int[7];
        Random random = new Random();
        int upperbound = 100; // generate random values from 0-100

        for (int i = 0; i < myArray.length; i++) {
            int x = random.nextInt(upperbound);
            myArray[i] = x;
        }
        System.out.println(Arrays.toString(myArray));
    }
}
